name: lunar-transformer-il
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - brotli-python=1.0.9=py312hd77b12b_8
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.11.26=haa95532_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - cuda-cccl=12.6.77=0
  - cuda-cccl_win-64=12.6.77=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=12.6.77=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.6=3
  - debugpy=1.6.7=py312hd77b12b_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.3=h5da7b33_0
  - freetype=2.12.1=ha860e81_0
  - giflib=5.2.2=h7edc060_0
  - idna=3.7=py312haa95532_0
  - importlib-metadata=8.5.0=pyha770c72_1
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.30.0=pyh7428d3b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.4=py312haa95532_1
  - jpeg=9e=h827c3e9_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=py312haa95532_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.7.77=0
  - libcurand-dev=10.3.7.77=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.39=h8cc25b3_0
  - libsodium=1.0.20=hc70643c_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=2.1.3=py312h2bbff1b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h2bbff1b_1
  - mkl_fft=1.3.11=py312h827c3e9_0
  - mkl_random=1.2.8=py312h0158946_0
  - mpmath=1.3.0=py312haa95532_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.2.1=py312haa95532_0
  - numpy=2.0.1=py312hfd52020_1
  - numpy-base=2.0.1=py312h4dde369_1
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.4.0=h2466b09_0
  - packaging=24.2=pyhd8ed1ab_2
  - parso=0.8.4=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.0.0=py312hb5480e2_0
  - pip=24.2=py312haa95532_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.48=pyha770c72_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.18.0=pyhd8ed1ab_1
  - pysocks=1.7.1=py312haa95532_0
  - python=3.12.7=h14ffc60_0
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - pytorch=2.5.1=py3.12_cuda11.8_cudnn9_0
  - pytorch-cuda=11.8=h24eeafa_6
  - pytorch-mutex=1.0=cuda
  - pywin32=305=py312h2bbff1b_0
  - pyyaml=6.0.2=py312h827c3e9_0
  - pyzmq=25.1.2=py312hd77b12b_0
  - requests=2.32.3=py312haa95532_1
  - setuptools=75.1.0=py312haa95532_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.13.2=py312haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.14=h0416ee5_0
  - tornado=6.4.2=py312h827c3e9_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.11.0=py312haa95532_0
  - ucrt=10.0.22621.0=h57928b3_1
  - urllib3=2.2.3=py312haa95532_0
  - vc=14.40=haa95532_2
  - vc14_runtime=14.42.34433=he29a5d6_23
  - vs2015_runtime=14.42.34433=hdffcdeb_23
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.44.0=py312haa95532_0
  - win_inet_pton=1.1.0=py312haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=ha9f60a1_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - astor==0.8.1
      - box2d==2.3.10
      - cloudpickle==3.1.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - farama-notifications==0.0.4
      - filelock==3.11.0
      - fonttools==4.55.3
      - gym==0.26.2
      - gym-notices==0.1.0
      - gymnasium==1.2.0
      - imageio==2.37.0
      - ipywidgets==8.1.7
      - joblib==1.4.2
      - json-tricks==3.17.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - matplotlib==3.9.4
      - nni==3.0
      - nvidia-ml-py==12.560.30
      - pandas==2.2.3
      - prettytable==3.12.0
      - psutil==6.1.0
      - pygame==2.6.1
      - pyparsing==3.2.0
      - pythonwebhdfs==0.2.3
      - pytz==2024.2
      - responses==0.25.3
      - schema==0.7.7
      - scikit-learn==1.6.0
      - scipy==1.14.1
      - simplejson==3.19.3
      - swig==4.3.1
      - threadpoolctl==3.5.0
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - typeguard==4.1.2
      - tzdata==2024.2
      - websockets==14.1
      - widgetsnbextension==4.0.14
prefix: C:\Work_Software\envs\noisy_ann
